-- [white-label] Neutralizado: esta migration promovia um super admin fixo (dev).
-- Numa instalacao nova, o PRIMEIRO cadastro vira super admin automaticamente
-- (logica em public.handle_new_user / claim_super_admin_if_empty). Sem seeds fixos.